version: "3"
services:
    api:
      environment:
      - DEBUG=docker
      - DB_USER=root
      - DB_NAME=safezone_db
      - DB_PASSWORD=root
      - DB_HOST=host.docker.internal:5432
      env_file:
      - .env.docker
      build: .
      ports: 
      - "8080:8080"
      volumes:
      - ./app:/code/app
      depends_on:
        - db
      
    db:
      image: postgres:15
      environment:
        - POSTGRES_PASSWORD=root
        - POSTGRES_USER=root
        - POSTGRES_DB=safezone_db
      ports:
        - 5432:5432

