"""created medical record

Revision ID: 3efd1b5c6d7a
Revises: 57e3ee952e2f
Create Date: 2023-06-07 18:48:25.867646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3efd1b5c6d7a'
down_revision = '57e3ee952e2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_records',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('user', sa.INTEGER(), sa.ForeignKey("users.id", ondelete="CASCADE"),
                    autoincrement=False, nullable=False,),
        sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='medical_records_pkey'),
    )
    op.create_index('ix_medical_records_id', 'medical_records', ['id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_medical_records_id', table_name='medical_records')
    op.drop_table('medical_records')
    # ### end Alembic commands ###
