"""GeoRestriction table

Revision ID: 57e3ee952e2f
Revises: 029f4742af99
Create Date: 2023-05-13 21:08:13.563164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e3ee952e2f'
down_revision = '029f4742af99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_restrictions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('radius', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('from_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group'], ['groups.id'], name='geo_restrictions_group_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='geo_restrictions_user_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='geo_restrictions_pkey')
    )
    op.create_index('ix_geo_restrictions_id', 'geo_restrictions', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geo_restrictions')
    #op.drop_index('ix_geo_restrictions_id', table_name='geo_restrictions')
    # ### end Alembic commands ###
