"""Create user table

Revision ID: 7fb069d39bb2
Revises: 
Create Date: 2023-02-22 14:25:45.940336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb069d39bb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('users',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('first_name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('last_name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(),
                              autoincrement=False, nullable=False,unique=True),
                    sa.Column('password', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='users_pkey')
                    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
